name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force_release_cli:
        type: boolean
        description: release packages/cli even if it normally wouldn't (e.g. due to release-please checks)
        default: false
      force_release_core:
        type: boolean
        description: release packages/core even if it normally wouldn't (e.g. due to release-please checks)
        default: false
      force_release_infra:
        type: boolean
        description: release packages/infra even if it normally wouldn't (e.g. due to release-please checks)
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      paths_released: ${{ steps.release.outputs.paths_released }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
          default-branch: main
          release-type: node
  npm-core:
    name: npm publish @web3-storage/content-claims
    needs: release
    if: contains(fromJson(needs.release.outputs.paths_released), 'packages/core') || inputs.force_release_core
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --workspace=packages/core
      - run: npm publish --access=public --workspace=packages/core --provenance
  npm-cli:
    name: npm publish @web3-storage/content-claims-cli
    needs: release
    if: contains(fromJson(needs.release.outputs.paths_released), 'packages/cli') || inputs.force_release_cli
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --workspace=packages/cli
      - run: npm publish --access=public --workspace=packages/cli --provenance
  npm-infra:
    name: npm publish @web3-storage/content-claims-infra
    needs: release
    if: contains(fromJson(needs.release.outputs.paths_released), 'packages/infra') || inputs.force_release_infra
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --workspace=packages/infra
      - run: npm publish --access=public --workspace=packages/infra --provenance
